# Change these first
owner: daqnext # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Meson Network
    url: https://meson.network
  - name: MCDN
    url: https://m-cdn.io
  - name: Meson Docs
    url: https://docs.meson.network
  - name: Meson Blog
    url: https://blog.meson.network
  - name: Content2049
    url: https://content2049.meson.network

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.meson.network
  # baseUrl: /upptime
  faviconSvg: https://cdn.jsdelivr.net/gh/daqnext/meson-docs/src/images/meson-logo.svg
  logoUrl: https://cdn.jsdelivr.net/gh/daqnext/meson-docs/src/images/meson-logo.svg
  theme: light
  name: Meson Network System Status
  introTitle: "Meson Network is committed to creating an efficient bandwidth marketplace on Web3."
  navbar:
    - title: Home
      href: https://meson.network/
    - title: Status
      href: /
    - title: Docs
      href: https://docs.meson.network/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
